### ISSUE TITLE
regarding focal length

### ISSUE THREAD

**Issue by pradeep8892** [rpng/android-camera-calibration#1]

**Comment by goldbattle** [comment]
`sir why are we setting the focal length 4.3 mm is this camera focal length.`

The goal was to possibility eliminate the phone changing the focal length. This of course is an *untested* feature, but that menu just gets the possible physical focal lengths of the camera and then tries to set that as the focus. The one thing that we don't want is a camera that has a varying focal length.

Let me know how your calibration goes, thanks!

**Comment by pradeep8892** [comment]
Ok thanks I got it. I have one question what is the unit of chekboard size
you have mentioned it as 5x6 7x8 is row X column of the checkboard

**Comment by goldbattle** [comment]
I think right now it is setup for circle grids.
https://github.com/rpng/android-camera-calibration/blob/master/app/src/main/java/io/rpng/calibration/managers/CameraCalibrator.java#L145-L149

I don't think the row vs column order matters.
For example this should be a 11x8 or an 8x11.
![acircles_pattern](https://user-images.githubusercontent.com/2222562/28534740-b9973e70-706f-11e7-86ae-57a373073351.png)

**Comment by pradeep8892** [comment]
ok thank you sir my doubt is clear now

**Comment by pradeep8892** [comment]
sorry to say you but i am not able to calibrate the camera i captured
around 13 images of check board and when i press the done button then it
displays the error "UNABLE TO CALIBRATE OPENCV CAMERA".  i captured the
images around the height of 1.5 feet in good brightness condition and the
whole display area is covered by the checkboard image only but still not
able to calibrate.

**Comment by goldbattle** [comment]
Are you able to see the points being extracted while looking at the paper?
You should be able to see good vs bad frame count in text on that screen.
You said you had 13 good images?

Usually I print it out on a 8x11 letter paper, and am about a foot above
the paper.

**Comment by pradeep8892** [comment]
no i did not get any point while capturing and selecting good vs bad
images. i tried it many times but not able to calibrate the camera i am
using lenovo phone api level 23. have you tried it in other cellphone also.
by the way thanks for answering my questions

**Comment by goldbattle** [comment]
I have only tried this on a nexas 6 phone.
It shoulds like the specified grid size is not correct if it is unable to
extract it and display it to you on the first screen.
