### ISSUE TITLE
distortion coefficient

### ISSUE THREAD

**Issue by pradeep8892** [rpng/android-camera-calibration#2]
i am not able to get the all 5 distortion coefficient as in your pictures its mentioned that you also got only 2 distortion coefficient. did you find all the distortion coefficient if yes can you please tell me how can i get this i am not able to find all the distortion coefficient.

**Comment by goldbattle** [comment]
The system uses opencv's [Calib3d.calibrateCamera](http://docs.opencv.org/java/2.4.4/org/opencv/calib3d/Calib3d.html#calibrateCamera(java.util.List%2C%20java.util.List%2C%20org.opencv.core.Size%2C%20org.opencv.core.Mat%2C%20org.opencv.core.Mat%2C%20java.util.List%2C%20java.util.List%2C%20int)). See this [line](https://github.com/rpng/android-camera-calibration/blob/master/app/src/main/java/io/rpng/calibration/managers/CameraCalibrator.java#L81) in the source code. I have it right now so that the other distortion points are [fixed by specifying flags](https://github.com/rpng/android-camera-calibration/blob/master/app/src/main/java/io/rpng/calibration/managers/CameraCalibrator.java#L47-L51).
```java
mFlags = Calib3d.CALIB_FIX_PRINCIPAL_POINT +
                Calib3d.CALIB_ZERO_TANGENT_DIST +
                Calib3d.CALIB_FIX_ASPECT_RATIO +
                Calib3d.CALIB_FIX_K4 +
                Calib3d.CALIB_FIX_K5;
```

To disable these I would probably do something alone the lines of the following (note this is untested).
```java
mFlags = 0x00000;
```

**Comment by pradeep8892** [comment]
Ya I have already looked on these things. And I do not want to disable all these parameters. I want to find all these distortion parameters ( k1,k2, p1,p2,k3). Right now I am not getting these. Can you tell me how can I get these.

**Comment by pradeep8892** [comment]
One thing also if I get the distortion coefficient how can I verify that this is correct

**Comment by goldbattle** [comment]
If you look at the opencv documentation I linked, those flags constrain the
calibration to have parts of the distortion constants set to zero. I would
recommend reading the documentation to clarify your understanding of what
they do. Right now there is no way in this program to verify the quality of
the calibration other then getting a small reprojection error. Hope that
helps.

**Comment by pradeep8892** [comment]
thanks i have got all the coefficient. but still i have one doubt what is
the exact  roll of setting flags. can you please clear my doubt

**Comment by goldbattle** [comment]
Setting flags are *flags* that enable or disable things.
The opencv [documentation](http://docs.opencv.org/java/2.4.4/org/opencv/calib3d/Calib3d.html#calibrateCamera(java.util.List%2C%20java.util.List%2C%20org.opencv.core.Size%2C%20org.opencv.core.Mat%2C%20org.opencv.core.Mat%2C%20java.util.List%2C%20java.util.List%2C%20int)) explains what they enable or disable.
```
CV_CALIB_USE_INTRINSIC_GUESS cameraMatrix contains valid initial values of fx, fy, cx, cy that are optimized further. Otherwise, (cx, cy) is initially set to the image center (imageSize is used), and focal distances are computed in a least-squares fashion. Note, that if intrinsic parameters are known, there is no need to use this function just to estimate extrinsic parameters. Use "solvePnP" instead.
CV_CALIB_FIX_PRINCIPAL_POINT The principal point is not changed during the global optimization. It stays at the center or at a different location specified when CV_CALIB_USE_INTRINSIC_GUESS is set too.
CV_CALIB_FIX_ASPECT_RATIO The functions considers only fy as a free parameter. The ratio fx/fy stays the same as in the input cameraMatrix. When CV_CALIB_USE_INTRINSIC_GUESS is not set, the actual input values of fx and fy are ignored, only their ratio is computed and used further.
CV_CALIB_ZERO_TANGENT_DIST Tangential distortion coefficients (p_1, p_2) are set to zeros and stay zero.
CV_CALIB_FIX_K1,...,CV_CALIB_FIX_K6 The corresponding radial distortion coefficient is not changed during the optimization. If CV_CALIB_USE_INTRINSIC_GUESS is set, the coefficient from the supplied distCoeffs matrix is used. Otherwise, it is set to 0.
CV_CALIB_RATIONAL_MODEL Coefficients k4, k5, and k6 are enabled. To provide the backward compatibility, this extra flag should be explicitly specified to make the calibration function use the rational model and return 8 coefficients. If the flag is not set, the function computes and returns only 5 distortion coefficients.
```
