### ISSUE TITLE
Conversion to yaml

### ISSUE THREAD

**Issue by jax79sg** [rpng/android-camera-calibration#5]
Hi,

Many camera based SLAM algorithms require a yaml camera calibration file. May i ask if your app produces the data to that? How should i create a yaml based on the data given? 

Thanks.

**Comment by goldbattle** [comment]
The app just displays the calibration results, so one can manually create a yaml file in the correct format if needed. Right now, that app doesn't save anything to file, so it just displays the results on the final screen.
